In [1]:
import numpy as np
import pandas as pd

In [86]:
durationDf = pd.read_csv('taxi-trip-duration/train.csv')
durationDf.columns

Index(['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag',
       'trip_duration'],
      dtype='object')

In [87]:
fareDf = pd.read_csv('data/fare/train.csv')
fareDf.columns

Index(['key', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

In [88]:
print(durationDf.shape, fareDf.shape)

(1458644, 11) (55423856, 8)

In [90]:
durationDfSampled = durationDf.sample(n=1400000, random_state=151)
durationDfSampled.describe()

,vendor_id,passenger_count,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,trip_duration
count,1.400000e+06,1.400000e+06,1.400000e+06,1.400000e+06,1.400000e+06,1.400000e+06,1.400000e+06
mean,1.534957e+00,1.664671e+00,-7.397348e+01,4.075093e+01,-7.397341e+01,4.075182e+01,9.595568e+02
std,4.987767e-01,1.314472e+00,7.190505e-02,3.303262e-02,7.167220e-02,3.599413e-02,5.303119e+03
min,1.000000e+00,0.000000e+00,-1.219333e+02,3.435970e+01,-1.219333e+02,3.218114e+01,1.000000e+00
25%,1.000000e+00,1.000000e+00,-7.399186e+01,4.073736e+01,-7.399133e+01,4.073590e+01,3.970000e+02
50%,2.000000e+00,1.000000e+00,-7.398174e+01,4.075411e+01,-7.397975e+01,4.075454e+01,6.620000e+02
75%,2.000000e+00,2.000000e+00,-7.396732e+01,4.076837e+01,-7.396301e+01,4.076982e+01,1.076000e+03
max,2.000000e+00,9.000000e+00,-6.133553e+01,5.188108e+01,-6.133553e+01,4.392103e+01,3.526282e+06

In [91]:
fareDfSampled = fareDf.sample(n=1400000, random_state=151)
fareDfSampled.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,1.400000e+06,1.400000e+06,1.400000e+06,1.399984e+06,1.399984e+06,1.400000e+06
mean,1.134587e+01,-7.249866e+01,3.991695e+01,-7.250809e+01,3.992564e+01,1.684754e+00
std,9.798813e+00,1.193258e+01,8.469628e+00,1.211631e+01,8.412398e+00,1.331596e+00
min,-5.300000e+01,-2.254350e+03,-3.084286e+03,-3.337173e+03,-2.584879e+03,0.000000e+00
25%,6.000000e+00,-7.399206e+01,4.073494e+01,-7.399139e+01,4.073401e+01,1.000000e+00
50%,8.500000e+00,-7.398180e+01,4.075265e+01,-7.398012e+01,4.075314e+01,1.000000e+00
75%,1.250000e+01,-7.396711e+01,4.076712e+01,-7.396363e+01,4.076811e+01,2.000000e+00
max,5.841600e+02,3.457626e+03,2.929240e+03,3.445035e+03,2.965617e+03,2.080000e+02

In [92]:
durationDfSampled.to_csv('data/duration/train_sampled.csv', index=False)
fareDfSampled.to_csv('data/fare/train_sampled.csv', index=False)

In [93]:
durationDfSampled = pd.read_csv('data/duration/train_sampled.csv')
fareDfSampled = pd.read_csv('data/fare/train_sampled.csv')

N = 1000000
rounded_points = 3

durationDfSampled = durationDfSampled.sample(n=N, random_state=151)
fareDfSampled = fareDfSampled.sample(n=N, random_state=151)


print(durationDfSampled.columns, durationDfSampled.shape)
print(fareDfSampled.columns, fareDfSampled.shape)

Index(['id', 'vendor_id', 'pickup_datetime', 'dropoff_datetime',
       'passenger_count', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'store_and_fwd_flag',
       'trip_duration'],
      dtype='object') (1000000, 11)
Index(['key', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object') (1000000, 8)

In [94]:
durationDfSampled['pickup_longitude_rounded'] = durationDfSampled['pickup_longitude'].round(rounded_points)
durationDfSampled['pickup_latitude_rounded'] = durationDfSampled['pickup_latitude'].round(rounded_points)
durationDfSampled['dropoff_longitude_rounded'] = durationDfSampled['dropoff_longitude'].round(rounded_points)
durationDfSampled['dropoff_latitude_rounded'] = durationDfSampled['dropoff_latitude'].round(rounded_points)

durationDfSampled.drop(['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'vendor_id'], axis=1, inplace=True)

durationDfSampled.head()

,id,pickup_datetime,dropoff_datetime,passenger_count,store_and_fwd_flag,trip_duration,pickup_longitude_rounded,pickup_latitude_rounded,dropoff_longitude_rounded,dropoff_latitude_rounded
1387222,id3340113,2016-04-23 23:49:26,2016-04-24 00:40:46,1,N,3080,-73.999,40.740,-73.880,40.822
949531,id2051959,2016-02-26 23:09:02,2016-02-26 23:25:19,2,N,977,-73.978,40.778,-74.005,40.739
588387,id3028136,2016-05-22 00:42:07,2016-05-22 01:01:01,1,N,1134,-73.952,40.711,-73.926,40.759
58518,id2616048,2016-01-31 11:54:37,2016-01-31 12:05:50,4,N,673,-74.016,40.707,-74.008,40.747
296407,id3572495,2016-06-26 18:35:57,2016-06-26 18:49:05,1,N,788,-73.981,40.733,-73.957,40.747

In [95]:
fareDfSampled['pickup_longitude_rounded'] = fareDfSampled['pickup_longitude'].round(rounded_points)
fareDfSampled['pickup_latitude_rounded'] = fareDfSampled['pickup_latitude'].round(rounded_points)
fareDfSampled['dropoff_longitude_rounded'] = fareDfSampled['dropoff_longitude'].round(rounded_points)
fareDfSampled['dropoff_latitude_rounded'] = fareDfSampled['dropoff_latitude'].round(rounded_points)

fareDfSampled.drop(['pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude'], axis=1, inplace=True)

fareDfSampled.head()

,key,fare_amount,pickup_datetime,passenger_count,pickup_longitude_rounded,pickup_latitude_rounded,dropoff_longitude_rounded,dropoff_latitude_rounded
1387222,2013-12-20 19:29:00.00000078,7.5,2013-12-20 19:29:00 UTC,1,-74.011,40.703,-74.010,40.712
949531,2009-10-01 15:42:30.0000003,8.1,2009-10-01 15:42:30 UTC,1,-73.952,40.769,-73.969,40.760
588387,2010-06-28 08:51:00.000000188,4.5,2010-06-28 08:51:00 UTC,1,-73.918,40.838,-73.922,40.837
58518,2012-10-02 19:49:38.0000003,6.5,2012-10-02 19:49:38 UTC,1,-73.964,40.768,-73.950,40.772
296407,2010-05-23 22:45:00.00000055,6.1,2010-05-23 22:45:00 UTC,5,-73.997,40.721,-74.000,40.735

In [96]:
durationUnique = durationDfSampled['pickup_longitude_rounded'].nunique()
fareUnique = fareDfSampled['pickup_longitude_rounded'].nunique()
print(durationUnique, fareUnique)

548 1079

In [97]:
durationDfSampled = durationDfSampled.groupby(['pickup_longitude_rounded', 'pickup_latitude_rounded', 'dropoff_longitude_rounded', 'dropoff_latitude_rounded', 'passenger_count']).agg({'trip_duration': 'median'}).reset_index()
fareDfSampled = fareDfSampled.groupby(['pickup_longitude_rounded', 'pickup_latitude_rounded', 'dropoff_longitude_rounded', 'dropoff_latitude_rounded', 'passenger_count']).agg({'fare_amount': 'median'}).reset_index()

print(durationDfSampled.shape, fareDfSampled.shape)

(867095, 6) (872348, 6)

In [98]:
# Merge duration and fare df on rounded coordinates
mergedDf = pd.merge(durationDfSampled, fareDfSampled, on=['pickup_longitude_rounded', 'pickup_latitude_rounded', 'dropoff_longitude_rounded', 'dropoff_latitude_rounded', 'passenger_count'], how='inner')
mergedDf.describe()

,pickup_longitude_rounded,pickup_latitude_rounded,dropoff_longitude_rounded,dropoff_latitude_rounded,passenger_count,trip_duration,fare_amount
count,126473.000000,126473.000000,126473.000000,126473.000000,126473.000000,1.264730e+05,126473.000000
mean,-73.976081,40.753639,-73.977687,40.754277,1.183850,7.674804e+02,9.233110
std,0.031296,0.022355,0.027004,0.022086,0.671001,5.578705e+03,8.339225
min,-74.194000,40.616000,-74.194000,40.602000,1.000000,1.000000e+00,-5.500000
25%,-73.991000,40.742000,-73.991000,40.742000,1.000000,3.310000e+02,5.300000
50%,-73.982000,40.756000,-73.981000,40.756000,1.000000,5.240000e+02,6.900000
75%,-73.969000,40.768000,-73.970000,40.768000,1.000000,8.280000e+02,9.500000
max,-73.422000,41.022000,-73.422000,41.022000,6.000000,1.763934e+06,152.450000

In [99]:
mergedDf.dropna(inplace=True)
mergedDf.drop_duplicates(inplace=True)
mergedDf.describe()

,pickup_longitude_rounded,pickup_latitude_rounded,dropoff_longitude_rounded,dropoff_latitude_rounded,passenger_count,trip_duration,fare_amount
count,126473.000000,126473.000000,126473.000000,126473.000000,126473.000000,1.264730e+05,126473.000000
mean,-73.976081,40.753639,-73.977687,40.754277,1.183850,7.674804e+02,9.233110
std,0.031296,0.022355,0.027004,0.022086,0.671001,5.578705e+03,8.339225
min,-74.194000,40.616000,-74.194000,40.602000,1.000000,1.000000e+00,-5.500000
25%,-73.991000,40.742000,-73.991000,40.742000,1.000000,3.310000e+02,5.300000
50%,-73.982000,40.756000,-73.981000,40.756000,1.000000,5.240000e+02,6.900000
75%,-73.969000,40.768000,-73.970000,40.768000,1.000000,8.280000e+02,9.500000
max,-73.422000,41.022000,-73.422000,41.022000,6.000000,1.763934e+06,152.450000

In [100]:
mergedDf.to_csv('data/merged/train_processed.csv', index=False)